# Generated by Django 4.2.1 on 2023-05-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
